packages:
  - name: contact
    functions:
      - name: submit
        runtime: php:8.2
        web: true
        limits:
          timeout: 10000
        environment:
          SMTP_HOST: smtpout.secureserver.net
          SMTP_PORT: "3535"
          SMTP_USERNAME: contactus@comwaretechs.com
          CONTACT_TO: contactus@comwaretechs.com
          SMTP_PASSWORD: "${SMTP_PASSWORD}"
