name: comware-static-site
static_sites:
  - name: web
    source_dir: /
    github:
      repo: qrauf/comwaretechs
      branch: logo-update
      deploy_on_push: true
    environment_slug: html
    index_document: index.html
ingress:
  rules:
    - match:
        path:
          prefix: /
      component:
        name: web
domains:
  - domain: comwaretechs.com
    type: PRIMARY
    zone: comwaretechs.com
